FROM python:3.8
COPY . /app
WORKDIR /app/restapi
RUN pip install -r ../requirements.txt
RUN python manage.py makemigrations
RUN python manage.py migrate
CMD ["python", "manage.py", "runserver", "8001"]